os: Visual Studio 2015

# version format
version: 1.0.4.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=

cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore src

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
    # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbracoidentity-oauth/api/v2/package
    symbol_server: https://www.myget.org/F/umbracoidentity-oauth/symbols/api/v2/package
    api_key:
      secure: gHDTL46KZcLzj6J8m//TJgaCOJCl9ixR//rXjO18HRlCsfPYYz7dU81u2D5zd+ZN
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # GitHub Deployment for releases
  - provider: GitHub
    auth_token:
      secure: yDxrRTveSScJA35MQTOaLYVjoPKFKl2bHBkG+JMZjiN0r7AfuUCxVU3CgW8Imu4h
    artifact: /.*\.zip/            # upload all Zip packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true        # deploy on tag push only

    # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: eSLiOXbGVrxSG+X7PV6qTTUZ5VzS9EFj5+EufaWPfd+QXkF6gc8rZ4mGoHIVp/fL
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true
